export NPROCS=8

echo This job has allocated $NPROCS nodes

echo  command to EXE:
PROGRAM="./scepticmpi -s5 -nr50 -nt10 -f -g -v2."
echo mpirun -l -np $NPROCS $PROGRAM
echo
#mpirun -l -np $NPROCS $PROGRAM


echo  command to EXE:
PROGRAM="./scepticmpi -s5 -nr50 -nt10 -f -g -v2. -kt1 -k1."
echo mpirun -l -np $NPROCS $PROGRAM
echo
#mpirun -l -np $NPROCS $PROGRAM


echo  command to EXE:
PROGRAM="./scepticmpi -s5 -nr50 -nt10 -f -g -v2. --bz0.1"
echo mpirun -l -np $NPROCS $PROGRAM
echo
#mpirun -l -np $NPROCS $PROGRAM


echo  command to EXE:
PROGRAM="./scepticmpi -s5 -nr50 -nt10 -f -g -v2. -kt1 -k0.01 --bz1. -cB0."
echo mpirun -l -np $NPROCS $PROGRAM
echo
#mpirun -l -np $NPROCS $PROGRAM


echo  command to EXE:
PROGRAM="./scepticmpi -s5 -nr50 -nt10 -f -g -kt1 -k0.01 --bz1. -v2."
echo mpirun -l -np $NPROCS $PROGRAM
echo
mpirun -l -np $NPROCS $PROGRAM


echo  command to EXE:
PROGRAM="./scepticmpi -s5 -nr50 -nt10 -f -g -kt1 -k0.01 --bz1. -v2. -vn2."
echo mpirun -l -np $NPROCS $PROGRAM
echo
mpirun -l -np $NPROCS $PROGRAM



sleep 1
exit


